server:
  port: 8003
  servlet:
    context-path: /storage
spring:
  application:
    name: storage-service
justbon:
  ds:
    dynamic:
      salt: justbond
      primary: account
      data-sources:
        account:
          username: root
          password: POCRqiCurCA=
          url: jdbc:mysql://10.0.9.101:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          driver-class-name: com.mysql.jdbc.Driver
          # 数据源类型：Druid
          type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: demo_group
  service:
    grouplist:
      default: 10.1.200.138:8091

  registry:
    type: nacos
    nacos:
      server-addr: 10.0.9.105:8848
      group : SEATA_GROUP
      username: "nacos"
      password: "nacos"
      application: seata-server
  config:
    type: nacos
    nacos:
      namespace:
      server-addr: 10.0.9.105:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"

